import = [ 
	"~/.config/alacritty/themes/gruvbox_dark.toml"
	]

window.dynamic_padding = true
window.padding = {x = 10,y = 10}
window.opacity = 0.8
window.blur = true

font.normal = {family = "BerkeleyMono Nerd Font", style = "Regular"}
font.bold = {family = "BerkeleyMono Nerd Font", style = "Bold"}
font.italic = {family = "BerkeleyMono Nerd Font", style = "Italic"}
font.size = 15.0

window.decorations_theme_variant = "Dark"
