import = [ 
	"~/.config/alacritty/themes/gruvbox_dark.toml"
	]

window.dynamic_padding = true
window.padding = {x = 10,y = 10}
window.opacity = 0.8
window.blur = true

font.normal = {family = "Berkeley Mono", style = "Regular"}
font.size = 14.0
